const eventsData = [
  {
      id: 1,
      date: "2024-05-05",
      track: "Circuit de Barcelona-Catalunya",
      country: "spain",
      countryName: "Испания",
      event: "Formula 1 - Гран-при Испании",
      description: "Главное событие сезона Формулы-1 в Испании. Трек известен своими высокоскоростными поворотами и является одним из самых технически сложных в календаре.",
      website: "https://www.circuitcat.com/en/",
      flag: "🇪🇸",
      trackImage: "🏁",
      coordinates: [41.5703, 2.2611]
  },
  {
      id: 2,
      date: "2024-05-12",
      track: "Circuit Paul Ricard",
      country: "france",
      countryName: "Франция",
      event: "GT World Challenge Europe",
      description: "Гоночная серия GT с участием лучших GT автомобилей Европы. Трек известен своими уникальными полосами безопасности.",
      website: "https://www.circuitpaulricard.com/",
      flag: "🇫🇷",
      trackImage: "🏁",
      coordinates: [43.2500, 5.8500]
  },
  {
      id: 3,
      date: "2024-05-19",
      track: "Nürburgring Nordschleife",
      country: "germany",
      countryName: "Германия",
      event: "24 часа Нюрбургринга",
      description: "Легендарная 24-часовая гонка на самой сложной трассе в мире. Северная петля Нюрбургринга - мечта каждого гонщика.",
      website: "https://www.nuerburgring.de/",
      flag: "🇩🇪",
      trackImage: "🏁",
      coordinates: [50.3400, 6.9500]
  },
  {
      id: 4,
      date: "2024-05-26",
      track: "Red Bull Ring",
      country: "austria",
      countryName: "Австрия",
      event: "MotoGP - Гран-при Австрии",
      description: "Гоночная серия MotoGP на живописном австрийском треке в Альпах. Высокоскоростная трасса с захватывающими видами.",
      website: "https://www.redbullring.com/",
      flag: "🇦🇹",
      trackImage: "🏁",
      coordinates: [47.2197, 14.7647]
  },
  {
      id: 5,
      date: "2024-06-02",
      track: "Automotodrom Brno",
      country: "czech",
      countryName: "Чехия",
      event: "MotoGP - Гран-при Чехии",
      description: "Исторический трек в Брно, один из самых любимых среди гонщиков MotoGP за свою техническую сложность.",
      website: "https://www.automotodrombrno.cz/",
      flag: "🇨🇿",
      trackImage: "🏁",
      coordinates: [49.1917, 16.4633]
  },
  {
      id: 6,
      date: "2024-06-09",
      track: "Circuit Zandvoort",
      country: "netherlands",
      countryName: "Нидерланды",
      event: "Formula 1 - Гран-при Нидерландов",
      description: "Возвращение Формулы-1 в Зандворт после долгого перерыва. Трек известен своими бандингами и атмосферой.",
      website: "https://www.circuit-zandvoort.nl/",
      flag: "🇳🇱",
      trackImage: "🏁",
      coordinates: [52.3889, 4.5408]
  },
  {
      id: 7,
      date: "2024-06-16",
      track: "Silverstone Circuit",
      country: "uk",
      countryName: "Великобритания",
      event: "Formula 1 - Гран-при Великобритании",
      description: "Исторический трек, где состоялась первая гонка Формулы-1 в 1950 году. Дом британского автоспорта.",
      website: "https://www.silverstone.co.uk/",
      flag: "🇬🇧",
      trackImage: "🏁",
      coordinates: [52.0786, -1.0169]
  },
  {
      id: 8,
      date: "2024-06-23",
      track: "Autódromo Internacional do Algarve",
      country: "portugal",
      countryName: "Португалия",
      event: "MotoGP - Гран-при Португалии",
      description: "Современный трек в Портимао с захватывающими перепадами высот и технически сложными поворотами.",
      website: "https://www.autodromodoalgarve.com/",
      flag: "🇵🇹",
      trackImage: "🏁",
      coordinates: [37.1311, -8.6417]
  },
  {
      id: 9,
      date: "2024-06-30",
      track: "Circuit de la Sarthe",
      country: "france",
      countryName: "Франция",
      event: "24 часа Ле-Мана",
      description: "Самая престижная гонка на выносливость в мире. Легендарная трасса, где скорость и надежность решают все.",
      website: "https://www.24h-lemans.com/",
      flag: "🇫🇷",
      trackImage: "🏁",
      coordinates: [47.9375, 0.2244]
  },
  {
      id: 10,
      date: "2024-07-07",
      track: "Hockenheimring",
      country: "germany",
      countryName: "Германия",
      event: "DTM - Немецкий чемпионат",
      description: "Популярная немецкая гоночная серия на историческом треке Хоккенхайм. Высокие скорости и захватывающие гонки.",
      website: "https://www.hockenheimring.de/",
      flag: "🇩🇪",
      trackImage: "🏁",
      coordinates: [49.3278, 8.5656]
  },
  {
      id: 11,
      date: "2024-07-14",
      track: "TT Circuit Assen",
      country: "netherlands",
      countryName: "Нидерланды",
      event: "MotoGP - Голландский TT",
      description: "Историческая гонка, известная как 'Собор скорости'. Один из самых быстрых треков в календаре MotoGP.",
      website: "https://www.ttcircuit.com/",
      flag: "🇳🇱",
      trackImage: "🏁",
      coordinates: [52.9617, 6.5233]
  },
  {
      id: 12,
      date: "2024-07-21",
      track: "Brands Hatch",
      country: "uk",
      countryName: "Великобритания",
      event: "BTCC - Британский чемпионат",
      description: "Популярная серия кузовных гонок на технически сложном треке с множеством подъемов и спусков.",
      website: "https://www.brandshatch.co.uk/",
      flag: "🇬🇧",
      trackImage: "🏁",
      coordinates: [51.3567, 0.2600]
  },
  {
      id: 13,
      date: "2024-07-28",
      track: "Circuito de Jerez",
      country: "spain",
      countryName: "Испания",
      event: "MotoGP - Гран-при Испании",
      description: "Классический трек в Хересе, где часто проводятся тесты и финальные гонки сезона MotoGP.",
      website: "https://www.circuitodejerez.com/",
      flag: "🇪🇸",
      trackImage: "🏁",
      coordinates: [36.7083, -6.0333]
  },
  {
      id: 14,
      date: "2024-08-04",
      track: "Sachsenring",
      country: "germany",
      countryName: "Германия",
      event: "MotoGP - Гран-при Германии",
      description: "Технически сложный трек с множеством левых поворотов. Любимый трек многих гонщиков MotoGP.",
      website: "https://www.sachsenring.de/",
      flag: "🇩🇪",
      trackImage: "🏁",
      coordinates: [50.8167, 12.6833]
  },
  {
      id: 15,
      date: "2024-08-11",
      track: "Salzburgring",
      country: "austria",
      countryName: "Австрия",
      event: "GT Masters Austria",
      description: "Высокоскоростной трек в живописных австрийских Альпах. Популярен среди GT серий.",
      website: "https://www.salzburgring.at/",
      flag: "🇦🇹",
      trackImage: "🏁",
      coordinates: [47.8500, 13.0500]
  }
];